// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfV_XG6KwfszHi5JlfMLBELZRh17FLqXM',
    appId: '1:328203245006:web:64e92273c7996e21b7079f',
    messagingSenderId: '328203245006',
    projectId: 'vyraimage',
    authDomain: 'vyraimage.firebaseapp.com',
    storageBucket: 'vyraimage.firebasestorage.app',
    measurementId: 'G-GY5TCRDLHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_oLo4xBZ68SZn-MoEtP1xcAf8waj3s_k',
    appId: '1:328203245006:android:e594001116f951a5b7079f',
    messagingSenderId: '328203245006',
    projectId: 'vyraimage',
    storageBucket: 'vyraimage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwnKrOgze8CmadyzfzyUBy1BE4_todas',
    appId: '1:328203245006:ios:0ba787f79ae4eac0b7079f',
    messagingSenderId: '328203245006',
    projectId: 'vyraimage',
    storageBucket: 'vyraimage.firebasestorage.app',
    iosClientId: '328203245006-a2lmruelpudbtvslju6k52ebs7pvb0v0.apps.googleusercontent.com',
    iosBundleId: 'com.kartikeyamishra.vyra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOwnKrOgze8CmadyzfzyUBy1BE4_todas',
    appId: '1:328203245006:ios:0ba787f79ae4eac0b7079f',
    messagingSenderId: '328203245006',
    projectId: 'vyraimage',
    storageBucket: 'vyraimage.firebasestorage.app',
    iosClientId: '328203245006-a2lmruelpudbtvslju6k52ebs7pvb0v0.apps.googleusercontent.com',
    iosBundleId: 'com.kartikeyamishra.vyra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfV_XG6KwfszHi5JlfMLBELZRh17FLqXM',
    appId: '1:328203245006:web:6fa720a281ccb27bb7079f',
    messagingSenderId: '328203245006',
    projectId: 'vyraimage',
    authDomain: 'vyraimage.firebaseapp.com',
    storageBucket: 'vyraimage.firebasestorage.app',
    measurementId: 'G-ZDNKRR3MX3',
  );
}
